export const PATH = {
  HOME: '/',
  SEARCH: '/search',
  PAGE404: '*',
  LOGIN: '/login',
  SIGNUP: '/login/signup',
  PLAYLIST: '/playlist',
  CREATEPLAYLIST: '/createplaylist',
  PROFILE: '/profile',
  USER_PROFILE: '/profile/:userId',
  EDITPROFILE: '/profile/editprofile',
  FOLLOW: 'follow',
  CHAT: '/chat',
  EDITPW: '/login/editpassword',
}
